name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
          
      - name: Download dependencies
        working-directory: ./backend
        run: go mod download
        
      - name: Run tests
        working-directory: ./backend
        run: go test -v ./...
        
      - name: Build application
        working-directory: ./backend
        run: go build -v ./...
