name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # バックエンドテスト・ビルド
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
          
      - name: Download dependencies
        working-directory: ./backend
        run: go mod download
        
      - name: Run tests
        working-directory: ./backend
        run: go test -v ./...
        
      - name: Build application
        working-directory: ./backend
        run: go build -v ./...

  # デプロイ（本番環境）
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: backend
    # mainブランチかつプッシュ時のみ実行
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          
      - name: Build and Deploy
        working-directory: ./backend
        run: |
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset